export const AddTodo = 'AddTodo'
export const ToggleTodo = 'ToggleTodo'
export const RemoveTodo = 'RemoveTodo'
export const ShowAll= 'ShowAll'
export const ShowCompleted = 'ShowCompleted'
export const ShowActive = 'ShowActive'
export const SetVisibilityFilter = 'SetVisibilityFilter'
